import {
  LayoutDashboard,
  Building2,
  Users,
  MessageSquare,
  Settings,
  LogOut,
  Bell,
  Search,
  UploadCloud,
  FileText,
  Activity,
  CheckCircle2,
  AlertTriangle,
  MoreVertical,
  Plus,
  Save,
  Download,
  Trash2,
  Bot,
  Zap,
  Wifi,
  WifiOff,
  Server,
  Smartphone,
  Check,
  X,
  Eye,
  Menu
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Building: Building2,
  Users: Users,
  Chat: MessageSquare,
  Settings: Settings,
  Logout: LogOut,
  Bell: Bell,
  Search: Search,
  Upload: UploadCloud,
  File: FileText,
  Activity: Activity,
  Check: CheckCircle2,
  Warning: AlertTriangle,
  More: MoreVertical,
  Plus: Plus,
  Save: Save,
  Download: Download,
  Trash: Trash2,
  Bot: Bot,
  Zap: Zap,
  Wifi: Wifi,
  WifiOff: WifiOff,
  Server: Server,
  Phone: Smartphone,
  CheckPlain: Check,
  XPlain: X,
  Eye: Eye,
  Menu: Menu
};